const express = require("express");
const fs = require("fs");
const path = require("path");

const app = express();

const PORT = 2000;

const OUTPUT_DIR = path.join(__dirname, "generated");
const PUBLIC_DIR = path.join(__dirname, "public");

const GB = 1_000_000_000;

const FILE_SIZES = {
    1: 1 * GB,
    2: 2 * GB,
    3: 3 * GB,
};

if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

app.use(express.json());
app.use(express.static(PUBLIC_DIR));


// --------------------------------------------------
// Get available files
// --------------------------------------------------

app.get("/api/files", (req, res) => {
    const files = fs.readdirSync(OUTPUT_DIR)
        .filter(file => file.endsWith(".txt"))
        .map(file => {
            const filepath = path.join(OUTPUT_DIR, file);
            const stats = fs.statSync(filepath);

            return {
                name: file,
                size: stats.size,
                sizeGB: (stats.size / GB).toFixed(2),
                downloadUrl: `/download/${encodeURIComponent(file)}`,
            };
        });

    res.json(files);
});


// --------------------------------------------------
// Generate file
// --------------------------------------------------

app.post("/api/generate", async (req, res) => {
    const size = Number(req.body.size);

    if (!FILE_SIZES[size]) {
        return res.status(400).json({
            error: "Size must be 1, 2, or 3 GB.",
        });
    }

    const targetSize = FILE_SIZES[size];

    const filename = `test-${size}gb.txt`;
    const filepath = path.join(OUTPUT_DIR, filename);

    try {

        // If the file already exists, don't generate again
        if (fs.existsSync(filepath)) {
            const stats = fs.statSync(filepath);

            return res.json({
                success: true,
                alreadyExists: true,
                filename,
                size: stats.size,
                downloadUrl: `/download/${encodeURIComponent(filename)}`,
            });
        }

        await generateFile(targetSize, filepath);

        const stats = fs.statSync(filepath);

        res.json({
            success: true,
            filename,
            size: stats.size,
            downloadUrl: `/download/${encodeURIComponent(filename)}`,
        });

    } catch (error) {

        console.error(error);

        res.status(500).json({
            error: error.message,
        });
    }
});


// --------------------------------------------------
// Download
// --------------------------------------------------

app.get("/download/:filename", (req, res) => {

    const filename = path.basename(req.params.filename);

    const filepath = path.join(OUTPUT_DIR, filename);

    if (!fs.existsSync(filepath)) {
        return res.status(404).send("File not found");
    }

    res.download(filepath, filename);
});


// --------------------------------------------------
// Delete file
// --------------------------------------------------

app.delete("/api/files/:filename", (req, res) => {

    const filename = path.basename(req.params.filename);

    const filepath = path.join(OUTPUT_DIR, filename);

    if (!fs.existsSync(filepath)) {
        return res.status(404).json({
            error: "File not found",
        });
    }

    fs.unlinkSync(filepath);

    res.json({
        success: true,
    });
});


// --------------------------------------------------
// File generator
// --------------------------------------------------

function generateFile(targetSize, filepath) {

    return new Promise((resolve, reject) => {

        const stream = fs.createWriteStream(filepath, {
            flags: "w",
            highWaterMark: 1024 * 1024,
        });

        const line =
            "This is test data generated by Node.js for large file testing.\n";

        const CHUNK_SIZE = 1024 * 1024;

        let chunkString = "";

        while (
            Buffer.byteLength(chunkString, "utf8") < CHUNK_SIZE
        ) {
            chunkString += line;
        }

        const chunk = Buffer.from(chunkString, "utf8");

        let written = 0;

        stream.on("error", reject);

        stream.on("finish", resolve);

        function write() {

            while (written < targetSize) {

                const remaining = targetSize - written;

                const data =
                    remaining >= chunk.length
                        ? chunk
                        : chunk.subarray(0, remaining);

                const canContinue = stream.write(data);

                written += data.length;

                if (!canContinue) {
                    stream.once("drain", write);
                    return;
                }
            }

            stream.end();
        }

        write();
    });
}


// --------------------------------------------------
// Start server
// --------------------------------------------------

app.listen(PORT, () => {

    console.log("");
    console.log("======================================");
    console.log("Large File Generator");
    console.log("======================================");
    console.log(`http://localhost:${PORT}`);
    console.log("");
});